### ISSUE TITLE
Indexing problem

### ISSUE THREAD

**Issue by baltrunasl** [jexp/batch-import#1]
I am totally new to neo4j and batch-importer, therefore, its most probably some stupid mistake.

I have these files:
Nodes: a
Edges: b

mac505213:socnet linas$ cat a 
Node    Rels    Propery
1   1   USER
90  1   USER

mac505213:socnet linas$ cat b 
Start   Ende    Type    Property
1   90  FRIEND  Property
90  1   FRIEND  Property

And I have this error:

java -server -Xmx4G -jar target/batch-import-jar-with-dependencies.jar target/db a b
Physical mem: 4096MB, Heap size: 3640MB
use_memory_mapped_buffers=false
neostore.propertystore.db.index.keys.mapped_memory=5M
neostore.propertystore.db.strings.mapped_memory=100M
neostore.propertystore.db.arrays.mapped_memory=215M
neo_store=/Users/linas/devel/batch-import/target/db/neostore
neostore.relationshipstore.db.mapped_memory=1000M
neostore.propertystore.db.index.mapped_memory=5M
neostore.propertystore.db.mapped_memory=1000M
dump_configuration=true
cache_type=none
neostore.nodestore.db.mapped_memory=200M

Importing 2 Nodes took 0 seconds 
0 seconds 
Exception in thread "main" org.neo4j.graphdb.NotFoundException: id=90
    at org.neo4j.kernel.impl.batchinsert.BatchInserterImpl.getNodeRecord(BatchInserterImpl.java:846)
    at org.neo4j.kernel.impl.batchinsert.BatchInserterImpl.createRelationship(BatchInserterImpl.java:439)
    at org.neo4j.batchimport.Importer.importRelationships(Importer.java:146)
    at org.neo4j.batchimport.Importer.main(Importer.java:52)

Interestingly, If I change 90 to 10 in both files, everything works fine. 
Most probably, I don't understand the input format. 

Please help me.

**Comment by jexp** [comment]
The first file only contains properties of the nodes to import property-name is in the header, value in the row.

The start,end-id values in the relationship-file refer to the row-numbers (1-based of the nodes-file).

**Comment by baltrunasl** [comment]
Thanks for a fast reply.

Row number! This was not clear from the documentation. I will try ASAP.

**Comment by baltrunasl** [comment]
In the example you have:

format nodes.csv
propname1   propname2
value1  value2

format rels.csv
start   end type    propname1   propname2
0   1   OWNS    value1  value2
1   2   IS_A    value1  value2

When start=0 its not really a pointer to a row number of the nodes.csv, its row number -1, as you also have a  header. Is it correct?

**Comment by jexp** [comment]
actually they refer to node-id's which are generated in a increasing sequence starting at 1 (0 is the reference node which already exists in the graph).

1 and up are the rows you specify in your nodes.csv
