### ISSUE TITLE
Add List in Node Property

### ISSUE THREAD

**Issue by sisodiakaran** [jexp/batch-import#106]
Hello,

I have a list `['item1', 'item2', 'item3']` and I would like to add this to a node property.

```
name: Node 1
node_property: ['item1', 'item2', 'item3']
```

Is there any option to do this, as when I add this to csv the list is imported as string.

Thanks in advance.

**Comment by jexp** [comment]
just use a comma separated string and the type "node_property:string_array" in the header.

**Comment by sisodiakaran** [comment]
Thanks @jexp, it worked smoothly...
