### ISSUE TITLE
View graph in Neo4j Browser after importing

### ISSUE THREAD

**Issue by raha001101** [jexp/batch-import#118]
I downloaded "batch_importer_22". Then prepared nodes.csv and rels.csv. Opened import.bat in windows and wrote "import.bat test.db nodes.csv rels.csv". It imported my files successfully with no errors. After all of these, I wanted to view my graph in neo4j browser, So I set the neo4j DB location. I faced error "Starting Neo4j Server failed: Error starting org.neo4j.kernel.EmbeddedGraphDatabase, C:\Users\NP\Documents\Neo4j\test.db".
I don't know what is the problem with this.

**Comment by jexp** [comment]
Which version of Neo4j did you use?

Can you check data/log/console.log and test.db/messages.log for any errors?

**Comment by raha001101** [comment]
My Neo4j version is "neo4j-community-2.0.4". In data/log path there is a txt file named README.txt includes :

"Neo4j Logs
Server logs, including:
- neo4j.log - graph database logging
- wrapper.log - logging for the service wrapper"
  
  And in db/messages.log there is one error :
  
  "ERROR [o.n.k.EmbeddedGraphDatabase]: Startup failed: Component 'org.neo4j.kernel.impl.transaction.XaDataSourceManager@70932490' was successfully initialized, but failed to start. Please see attached cause exception.: Component 'org.neo4j.kernel.impl.nioneo.xa.NeoStoreXaDataSource@27656044' was successfully initialized, but failed to start. Please see attached cause exception.: Failed to start Neo4j with an older data store version. To enable automatic upgrade, please set configuration parameter "allow_store_upgrade=true""

I set configuration parameter "allow_store_upgrade=true". But the error is as past.

**Comment by jexp** [comment]
What it says: you have to use neo4j-community-2.2.2 for using it with batch-importer-2.2
