### ISSUE TITLE
Behaviour for index nodes

### ISSUE THREAD

**Issue by stephanf** [jexp/batch-import#12]
Hi,

I had some trouble getting an index up and running with the batch-importer. I got no error and no warning.

More or less by accident, I realized that I had a misspelled the file names of the indexes.

But only by looking into the source code I was able to understand why I got no feedback, if the index csv file does not exist the Importer does not prompt an error he just returns with no message:

if (!indexFile.exists()) return;

In importIndex(...), may be calling the Report here would help a bit.

Cheers,
Stephan Froede

**Comment by jexp** [comment]
fixed
