### ISSUE TITLE
An exception occured while executing the Java class. More than one element in org.mapdb.Bind$5$1@46248627. First element is '983727989' and the second element is '997379223' 

### ISSUE THREAD

**Issue by Duanexiao** [jexp/batch-import#126]
Why this error? I found that these two element are not the same.One is "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0",
and the other is "000000000000000".Looking for your reply.Many thanks.

**Comment by jexp** [comment]
Please use the built-in import tools in Neo4j, i.e. `neo4j-import` or `neo4j-admin import`
