### ISSUE TITLE
Node Types?

### ISSUE THREAD

**Issue by KevinBurton** [jexp/batch-import#29]
How are nodes of different types handled? For example I have order nodes, product nodes, and address nodes. One could envision the relationship between an order node and product node as ORDERED (with maybe the date and quantity as properties of the relationship). One ccould also envision a relationship between the address node and order node as SHIPPED-TO. There are obvious different properties for each of these node types. If I try to do this with several different batch imports then the node id invariably gets duplicated. Ideas?

**Comment by EnricGTorrents** [comment]
That's right Kevin, I am having the very same issue. Not sure could it be implemented but there should be an option to add some kind of markup code in the csv to tell the importer to switch to a different kind of node, with a different set of properties, i.e:

> ---- Name Type       Age
> Georges Abi-Saab    Law Professional     80
> Ronny Abraham   Law Professional      36
> ---- Name Type         Headquarters
> Ukulele Orchestra of Great Britain     Orchestra     London
> (...)

And so on.

**Comment by jexp** [comment]
The CSV importer is not deduplicating nodes during the import that would adversely affect performance a lot.

Supporting different sets of attributes is easy. Just leave the fields blank that are not relevant for the current node.

**Comment by EnricGTorrents** [comment]
Thanks, that's true, I was just gonna edit my post adding the quote "Just put them all into one nodes file, you can have any attribute not having a value in a certain row, it will then just be skipped.".
