### ISSUE TITLE
Importing Foreign Language Characters

### ISSUE THREAD

**Issue by EnricGTorrents** [jexp/batch-import#30]
I am having a hard time importing a non-english database. A couple of examples to illustrate the problem: "Karl-Heinz Böckstiegel" imports as "Karl-Heinz B��ckstiegel", "Laurent Lévy" imports as "Laurent L��vy". The same applies to exporting text in Chinese, etc. Not sure if I am doing anything wrong (I am using UTF-8 .csv files), or missing any encoding parameter of batch-import, but if not it would be really useful to get this issue fixed.

**Comment by jexp** [comment]
Good point, so far I only used US-ASCII.csv files. I can look into it.

Did you use the parallel batch-inserter or the sequential one?

**Comment by EnricGTorrents** [comment]
Thanks for the quick reply! I am using the sequential one, haven't tried the parallel yet.

**Comment by jexp** [comment]
@d0840001 Can you try to run it with: -Dfile.encoding=UTF-8

**Comment by EnricGTorrents** [comment]
Done, it works perfectly. Thanks! :)
