### ISSUE TITLE
Compatibility with v2.0.0M02

### ISSUE THREAD

**Issue by milani** [jexp/batch-import#34]
Hi,

Is there any chance to update the repo to support new neo4j v2.0.0-M02?

**Comment by jexp** [comment]
Will try to find time to look into it. The batch-inserter changed a bit. But will make it work.

**Comment by sheymann** [comment]
Hi,

Can you at least upgrade to 1.9? The current kernel is still 1.8.2.

**Comment by jexp** [comment]
It is updated to 2.0.0 final.

**Comment by milani** [comment]
Thank you!
