### ISSUE TITLE
Label support

### ISSUE THREAD

**Issue by tobycraig** [jexp/batch-import#35]
Any idea if/when Neo4j 2.0 labels will be supported by the batch importer?

**Comment by jexp** [comment]
I'm currently working on indexing, labels and 2.0 will be next.

**Comment by guemon** [comment]
Could you tell me how to use schema index by the batch importer?

**Comment by jexp** [comment]
Schema indexes cannot be used in the Neo4j Batch-Inserter API.

Label support works with a column called, `label:label`
