### ISSUE TITLE
Duplication of nodes

### ISSUE THREAD

**Issue by lionleaf** [jexp/batch-import#38]
I'm importing around 350k nodes, and have a nodes.csv file with 354k lines. The importer runs just fine, and nodes are created. However, there it imports (and reports importing) over 700k nodes. Upon investigation, every node I looked at had an exact duplicate but with a difference of 1 in the id. All the relations are also completely wrong, but this clearly because they refer to the correct node ids. 
I've tried with and without automatic node indexing.

**Comment by jexp** [comment]
Thanks for reporting, I look into it.

**Comment by wkillerud** [comment]
I went back in the commit history to commit f65a5ca346dac960d8661ece3bf9ea89393c5c19, and confirmed that it imports the correct amount of nodes using a small test data set. The same dataset experiences the problem described above by @lionleaf with the latest commit.

Edit: 
The nodes.csv file I used for testing:
name    dummy
Hurr    Durr
Foo Fighters
Black   Debbath

My rels.csv:
start   end type
1   2   IS_BAND
2   3   IS_BAND

Result output from latest commit:
Importing 7 Nodes took 0 seconds 
Importing 5 Relationships took 0 seconds 
Total import time: 1 seconds 

Result output from f65a5ca346dac960d8661ece3bf9ea89393c5c19:
Importing 3 Nodes took 0 seconds 
Importing 2 Relationships took 0 seconds 
Total import time: 0 seconds
