### ISSUE TITLE
Unmatched quote in value causes AbstractLineData::parse to try to slurp up whole file before continuing to next line

### ISSUE THREAD

**Issue by donaldguy** [jexp/batch-import#50]
Seems to deal with matched quotes fine, but I had an import that was hanging and I eventually tracked it to badly sanitized data from the MySQL dump

In my case it was specifically in the first column in the row, but I don't know if that matters... 

... I might dig into more details of this later, or might not.

Thanks for the importer, though.

**Comment by jexp** [comment]
Any suggestion on what we can do? The importer now uses opencsv by default which allows multi-line entries in quotes.

**Comment by donaldguy** [comment]
Minimally some amount of pitfall documentation. While I admit it is a common thing to CSV parsing, I didn't see anything about quotation in the readme, I assumed it was unsupported/not a concern until it caused a problem.

Given the insistence towards tab (^I) field-separation (and newline record separation), before I dove into the source, I generally assumed tokenization would be performed at the line and tab level, and that generally tabs and newlines would not be accepted as a character contained therein (at least not without explicit per-character escaping)

​If it is the aim to support inline tabs/new lines through quoting, that should probably be documented. Or more aggressively, perhaps a warning should be logged when such are encountered. 

Really the main problem was that this happened within the first 10000 records, so I had no output beyond a usage note and "Using existing configuration file", and couldn't tell if anything was happening at all until I attached a debugger

**Comment by fredbenenson** [comment]
Just wanted to say I ran into this as well, and it also took quite a big of debugging to figure it out, so I'm with @donaldguy re: pitfall documentation.

I also agree that Iif you're doing a batch-import, it is perfectly reasonable to assume that individual rows / entries are new-line delimited (many other massive import tools do this), so maybe there's away to turn that "feature" off in opencsv.

Otherwise, thanks for the great tool!
