### ISSUE TITLE
Node id feature: NotFoundException

### ISSUE THREAD

**Issue by Tooa** [jexp/batch-import#59]
Hey, 
Instead of referring to row numbers in my csv file  I want to refer to node id's. So my node file looks like:

```
i:id    identifier:string:TokenNode
....        ....
99          %$% 
....        ....
```

and the rel file:

```
start   end type
99       98 OCCURENCE
```

I run the importer with: 

```
 mvn test-compile exec:java -Dexec.mainClass="org.neo4j.batchimport.Importer"   -   Dexec.args="batch.properties target/graph.db nodes.csv rels.csv"
```

And the following exception is returned: 

```
    Caused by: org.neo4j.graphdb.NotFoundException: id=99
```

But the Id is in my file and the Importer just imports the first node with id 1 and crashs with the first relation above. 

Regards Toa

**Comment by kylemarkwilliams** [comment]
This successfully worked for me today using the 2.0 branch. Maybe you could try with that?
