### ISSUE TITLE
Custom Separator for Arrays

### ISSUE THREAD

**Issue by dav009** [jexp/batch-import#62]
Arrays are by default separated by `,`. I'm dealing with many values containing `,` so it would be nice if there is a field in the config allowing to change the Separator.

**Comment by jexp** [comment]
What kind of separator did you think of? Just curious. Sure we can make this configurable. Feel free to issue a pull request w/ test, then it will be in there faster :)

**Comment by dav009** [comment]
Well, for my case `|` turned out to be a good separator. My nodes have a property  `name` which is basically an array of Name entity mentions which sometimes include commas for example: "Paris, France"

I already got a fork with the fix :) I will add a PR soon.

**Comment by jason64** [comment]
Could you please merge this changes into the 20 branch?

**Comment by etheleon** [comment]
^2nd that

**Comment by jexp** [comment]
done
