### ISSUE TITLE
Support indexing of array properties?

### ISSUE THREAD

**Issue by gkop** [jexp/batch-import#67]
I can explicitly index arbitrary array properties in neography, and used to be able to use @maxdemarzi's batch-import fork circa February 2013 to load and index string array properties.

It seems now that Max blew away his old, slightly hacky code for loading and indexing string array properties. At least, with master branch here I can load arbitrary array properties easily but I haven't yet figured out how to index them. (I've tried the auto-index option as well as explicit indexing; with the explicit index I tried both a comma-separated column and also with a new row for each element).

Is indexing array properties supported in any way by the current master tree?

**Comment by maxdemarzi** [comment]
I think the code lives on the blog post

**Comment by linkwoman** [comment]
link please?

**Comment by maxdemarzi** [comment]
It's all there actually.

https://github.com/jexp/batch-import/blob/master/src/test/java/DataTest.java#L62 and
https://github.com/jexp/batch-import/blob/master/src/main/java/org/neo4j/batchimport/importer/Type.java#L162

use "string_array" for the type and commas for the separator.

**Comment by gkop** [comment]
Thanks @maxdemarzi ! Some other change to the code since 32df666a671f2 broke my indexing :( But I will figure it out!
