### ISSUE TITLE
How to set up dev environment?

### ISSUE THREAD

**Issue by gkop** [jexp/batch-import#68]
When I import into Eclipse, the result is quite ugly: 
![screenshot-java - batch-import-src-main-java-org-neo4j-batchimport-importer java - eclipse sdk](https://f.cloud.github.com/assets/222582/1688258/e63a8dce-5e03-11e3-9608-f7ebe1252a7d.png)

```
$ java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)
```

The reason I ask is that I want write a failing test for the functionality of indexing array properties, and then try to fix this functionality.

Thanks!

**Comment by jexp** [comment]
Perhaps an dependency issue? Did you import the project dependencies using the maven pom.xml ?

**Comment by gkop** [comment]
Thanks @jexp ! Re-cloning seems to have fixed the command line test (still running) and executing `$ mvn eclipse:eclipse` before importing into eclipse has made eclipse much prettier.

**Comment by gkop** [comment]
Spoke too soon, it only looked cleaner in eclpise cause it didn't build at all -

![screenshot-java - eclipse sdk](https://f.cloud.github.com/assets/222582/1688440/ddac7326-5e07-11e3-8d13-14e1fa4d1086.png)

**Comment by gkop** [comment]
Nevermind, found help here - http://el.web.id/unbound-classpath-variable-m2_repo-in-eclipse-135
