### ISSUE TITLE
output of sample/import.sh not compatible with neo4j 2.0

### ISSUE THREAD

**Issue by sagnik** [jexp/batch-import#69]
I was trying to convert a graph using sample/import.sh. It seems that the output (target/graph.db) is not compatible with neo4j-community-2.0.0-M06, however, it is compatible with neo4j-community-1.8.3.

**Comment by jexp** [comment]
I don't know what you mean by "convert".

Did you use the 2.0 branch of the project?

**Comment by sagnik** [comment]
Nope. I was using master. OK, I will try with 2.0 branch.

**Comment by sagnik** [comment]
I am closing this, 2.0 branch works perfectly.
