### ISSUE TITLE
Exception thrown unless EOL are dos style

### ISSUE THREAD

**Issue by johowie** [jexp/batch-import#7]
It seems that files with line endings using just 'newline'  throws an exception (see below).

when i process the .csv to have carriage-returns in additions to a newline the script works.

csv files were created on osx mysql workbench - i added the newlines with :
$perl -pe 's/\r\n|\n|\r/\r\n/g' nodes.csv > newNodesFile.csv
and then the script worked.

FROM TERMINAL:
$java -server -Xmx4G -jar target/batch-import-jar-with-dependencies.jar target/graph.db bnodes.csv rels.csv

Using Existing Configuration File
remote_logging_host=127.0.0.1
forced_kernel_id=
read_only=false
neo4j.ext.udc.host=udc.neo4j.org
logical_log=nioneo_logical.log
online_backup_enabled=false
remote_logging_port=4560
gc_monitor_threshold=200ms
array_block_size=120
load_kernel_extensions=true
neostore.relationshipstore.db.mapped_memory=1000M
node_auto_indexing=false
intercept_committing_transactions=false
keep_logical_logs=true
dump_configuration=true
gc_monitor_wait_time=100ms
cache_type=none
intercept_deserialized_transactions=false
neostore.nodestore.db.mapped_memory=200M
neo4j.ext.udc.first_delay=600000
neo4j.ext.udc.reg=unreg
lucene_searcher_cache_size=2147483647
neo4j.ext.udc.interval=86400000
use_memory_mapped_buffers=true
rebuild_idgenerators_fast=true
neostore.propertystore.db.index.keys.mapped_memory=5M
neostore.propertystore.db.strings.mapped_memory=200M
neostore.propertystore.db.arrays.mapped_memory=130M
neo_store=neostore
logging.threshold_for_rotation=104857600
neostore.propertystore.db.index.mapped_memory=5M
backup_slave=false
neostore.propertystore.db.mapped_memory=1000M
gcr_cache_min_log_interval=60s
relationship_grab_size=100
relationship_auto_indexing=false
string_block_size=120
lucene_writer_cache_size=2147483647
node_cache_array_fraction=1.0
grab_file_lock=true
remote_logging_enabled=false
allow_store_upgrade=false
neo4j.ext.udc.enabled=true
execution_guard_enabled=false
relationship_cache_array_fraction=1.0
online_backup_port=6362

Total import time: 0 seconds 
Exception in thread "main" org.neo4j.graphdb.NotFoundException: id=29
    at org.neo4j.unsafe.batchinsert.BatchInserterImpl.getNodeRecord(BatchInserterImpl.java:902)
    at org.neo4j.unsafe.batchinsert.BatchInserterImpl.createRelationship(BatchInserterImpl.java:455)
    at org.neo4j.batchimport.Importer.importRelationships(Importer.java:243)
    at org.neo4j.batchimport.Importer.main(Importer.java:86)

**Comment by jexp** [comment]
Did you create the files on the same system that you're running the import?
It uses the default java behavior for treating newlines (which is more or less system specific).

**Comment by johowie** [comment]
all done in OSX
.csv files were created by mysql workbench
batch-import run in osx bash terminal

**Comment by johowie** [comment]
also, i only noticed this behaviour when the last column had 1 or more empty values

**Comment by jexp** [comment]
Can you provide a project or gist with sample files?

**Comment by johowie** [comment]
I may have been mistaken about the EOL ... it was probably too late in the evening to be doing tests !
Upon retesting it is only occurring when the last column contains one or more empty values.
apologies for not testing better before posting.
test data at:  
     git://gist.github.com/3759175.git

**Comment by johowie** [comment]
I also note that I am getting a different error now. as the error mentioned in the gist i posted is:
Exception in thread "main" java.util.NoSuchElementException
    at java.util.StringTokenizer.nextToken(StringTokenizer.java:332)
    at org.neo4j.batchimport.Importer$Data.split(Importer.java:153)
    at org.neo4j.batchimport.Importer$Data.update(Importer.java:169)
    at org.neo4j.batchimport.Importer.importNodes(Importer.java:228)
    at org.neo4j.batchimport.Importer.main(Importer.java:85)

it does not mention a "NotFoundException: id=29"

I had another bug in what i was doing earlier and it involved a mysql id field skipping values which coincidently was the values 29,30,31.
I cant seem to recreate this initial error

**Comment by jexp** [comment]
@johowie can you check if the fix in #13 also solved the issue for you?

**Comment by johowie** [comment]
I can't check right now, but if it fixed the error when there were null values on in the last column. then I expect it would have fixed the problem for me too.

Thanks for sharing your work @jexp !
