### ISSUE TITLE
Issue compiling 20 branch

### ISSUE THREAD

**Issue by paulgb** [jexp/batch-import#70]
The master branch compiles fine for me, but when I attempt to compile I get the error:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/paulbutler/batch-import/src/main/java/org/neo4j/batchimport/structs/Property.java:[22,18] error: cannot find symbol
```

It looks like Property.java is looking for `PropertyBlock.clean()` which works in master because master includes its own copy of PropertyBlock which implements clean, but 20 relies on the neo4j implementation of PropertyBlock which does not implement `clean`.

It seems other people (eg. @66) have compiled without issue, am I doing something wrong?

**Comment by kmorey** [comment]
I also can't get the 20 branch to build for this reason

**Comment by cescalante-carecloud** [comment]
Hello from 66,
When did you acquire your branch 20? 
I'm going to download the latest version of 20 and see if I can reproduce.

**Comment by paulgb** [comment]
I checked it out earlier today.

**Comment by cescalante-carecloud** [comment]
Yeah, I'm getting the same error.

The version I was talking about in that other thread still works as expected:
https://github.com/cescalante-carecloud/batch-import/tree/20

The only minor gripe I had was with that particular snapshot of 20 was/is that comma delimiting wasn't working out and my text editor just hates tabs, so I ended up using | as my delimiter. 

![screen shot 2013-12-11 at 9 46 44 pm](https://f.cloud.github.com/assets/5851735/1730213/ba938792-62d7-11e3-8b92-c6127c190bee.png)

edit: English is my primary language, I swear, I just can't write today.

**Comment by paulgb** [comment]
Thanks, I'll check that out. I ended up having success using the non-20 version and allowing neo4j to update from the old version.

**Comment by zhiboz** [comment]
I am having the same issue as paulgb has. Very interested to know how you folks get around this issue. Thanks!

**Comment by jexp** [comment]
Sorry, I fixed it. Turned out my `.gitignore` accidentally ignored some of the source files :(

**Comment by kmorey** [comment]
Thanks @jexp !
