### ISSUE TITLE
double quotes character causes batch import branch 20 to skip the line

### ISSUE THREAD

**Issue by etheleon** [jexp/batch-import#75]
Hi 

below is the culprit line in my nodes file

ko:string:koid._name.___definition._____l:label.pathway:string_array.___pathway.name:string_array
ko:K00002.______rpoA2.__DNA-directed RNA polymerase subunit A" [EC:2.7.7.6].____ko._____path:ko00230|path:ko00240|path:ko01100._Purine metabolism|Pyrimidine metabolism|Metabolic pathways

i noticed if i escaped the double quote right after A, ie. subunit A\" it works fine.

**Comment by jexp** [comment]
Ok, does the escaping work for you? Then I would close this issue.
