### ISSUE TITLE
Feature request: typing support for index properties and numeric indices

### ISSUE THREAD

**Issue by amergin** [jexp/batch-import#8]
Currently it seems that all the index properties are typed as string. It would be great to have a typing support for these as well and be able to build numeric indices as explained in Neo4j docs (http://docs.neo4j.org/chunked/stable/indexing-lucene-extras.html).

**Comment by jexp** [comment]
Numeric indexes are tricky b/c they have to be queried specially (with RangeQueries or ValueContext.numeric()) what is your use-case?

**Comment by jexp** [comment]
I think numeric indexes cause more problems than they solve, @amergin would you agree here and can we close this issue?

**Comment by amergin** [comment]
Agreed, closed.
