### ISSUE TITLE
Labels not being created

### ISSUE THREAD

**Issue by amoranzea** [jexp/batch-import#88]
Hi,

I'm trying to create nodes with labels using the importer but, after running the importer without any warning or error, the labels are not being created in Neo4j 2.0. I am using the branch 20 and I am wondering if labels are not supported yet or I'm missing a configuration in batch.properties. 

Here is an example of the nodes.csv:

node_id:int:plants  l:label plantnumber 
9   Plant    123
10  Plant    456
11  Plant    678

**Comment by cescalante-carecloud** [comment]
This worked for me. I use the pipe as a delimiter:

plant_nodes.csv (I put it in a folder called sample2):

```
node_id:int:plants|plantnumber:int|l:label
1|354|plant
2|53|plant
3|55|plant
```

import.sh:

```
NODES=${1-nodes.csv}
shift
RELS=${1-rels.csv}
shift
echo "running test import"
mvn test-compile exec:java -Dexec.mainClass="org.neo4j.batchimport.Importer" \
 -Dexec.args="sample2/batch.properties ../NEO4J_HOME/data/graph.db 
sample2/plant_nodes.csv $RELS" | grep -iv '\[\(INFO\|debug\)\]'
```

batch.properties included:

```
batch_import.csv.delim=|
batch_import.node_index.plants=exact
```

**Comment by jexp** [comment]
Right, was your delimiter a space or tab @amoranzea ?

**Comment by amoranzea** [comment]
Still doesn't work for me and I'm wondering if one of the following steps is incorrect:

batch.properties

<pre><code>
dump_configuration=false
cache_type=none
use_memory_mapped_buffers=true
neostore.nodestore.db.mapped_memory=100M
neostore.relationshipstore.db.mapped_memory=500M
neostore.propertystore.db.mapped_memory=1G
neostore.propertystore.db.strings.mapped_memory=200M
neostore.propertystore.db.arrays.mapped_memory=0M
neostore.propertystore.db.index.keys.mapped_memory=15M
neostore.propertystore.db.index.mapped_memory=15M
batch_import.node_index.plants=exact
batch_import.node_index.pots=exact
batch_import.csv.delim=|
</code></pre>

plant_nodes.csv

<pre><code>
node_id:int:plants|plant_number:string|l:label
1|1234|Plant
2|567|Plant
3|891|Plant
</code></pre>

pot_nodes.csv

<pre><code>
node_id:int:pots|name:string|l:label
1|pot1|Pot
2|pot2|Pot
3|pot3|Pot
</code></pre>

plant_rels.csv

<pre><code>
node_id:int:plants|node_id:int:pots|type
1|2|SUBMITTED
2|3|SUBMITTED
</code></pre>

maven command

<pre><code>
mvn clean compile exec:java -Dexec.mainClass="org.neo4j.batchimport.Importer" -Dexec.args="sample2/batch.properties ../NEO4J_HOME/data/graph.db sample2/plant_nodes.csv,sample2/pot_nodes.csv sample2/plant_rels.csv" | grep -iv '\[\(INFO\|debug\)\]'
</code></pre>

console output

<pre><code>
Usage: Importer data/dir nodes.csv relationships.csv [node_index node-index-name fulltext|exact nodes_index.csv rel_index rel-index-name fulltext|exact rels_index.csv ....]
Using: Importer sample2/batch.properties ../NEO4J_HOME/data/graph.db sample2/plant_nodes.csv,sample2/pot_nodes.csv sample2/plant_rels.csv
Using Existing Configuration File
Importing 3 Nodes took 0 seconds 
Importing 3 Nodes took 0 seconds 
Importing 2 Relationships took 0 seconds 
Total import time: 0 seconds 
</code></pre>

Before running the importer command, I'm stopping neo4j and deleting all files under ../NEO4J_HOME/data/graph.db. After running the importer, If I don't have the following configuration in neo4j.properties config file, when I try to start neo4j it crashes asking for this property to be added. 

<pre><code>
# Enable this to be able to upgrade a store from an older version
allow_store_upgrade=true
</code></pre>

Can you see something wrong on my procedure?

**Comment by jexp** [comment]
Why do you have node id and plant id?

Try string as type for node id

Otherwise use id:id

Without a legacy index

Sent from mobile device

Am 13.02.2014 um 07:39 schrieb Alejandro Moran notifications@github.com:

**Comment by amoranzea** [comment]
I just changed the example (see below) and still doesn't work. I'm wondering if there is a configuration that I'm not considering either on Neo4j or the importer.

plant_nodes.csv
<pre><code>
name|l:label|age|works_on
Michael|Person,Father|37|neo4j
Selina|Person,Child|14
Rana|Person,Child|6
Selma|Person,Child|4
</pre></code>

plant_rels.csv
<pre><code>
start|end|type|since|counter:int
0|1|FATHER_OF|1998-07-10|1
0|2|FATHER_OF|2007-09-15|2
0|3|FATHER_OF|2008-05-03|3
2|3|SISTER_OF|2008-05-03|5
1|2|SISTER_OF|2007-09-15|7
</pre></code>

batch.properties
<pre><code>
dump_configuration=false
cache_type=none

use_memory_mapped_buffers=true
neostore.nodestore.db.mapped_memory=100M
neostore.relationshipstore.db.mapped_memory=500M
neostore.propertystore.db.mapped_memory=1G
neostore.propertystore.db.strings.mapped_memory=200M
neostore.propertystore.db.arrays.mapped_memory=0M
neostore.propertystore.db.index.keys.mapped_memory=15M
neostore.propertystore.db.index.mapped_memory=15M

batch_import.csv.delim=|
</pre></code>

maven command
<pre><code>
mvn clean compile exec:java -Dexec.mainClass="org.neo4j.batchimport.Importer" -Dexec.args="sample2/batch.properties ../NEO_HOME/data/graph.db sample2/plant_nodes.csv sample2/plant_rels.csv" | grep -iv '[(INFO|debug)]'
</pre></code>

output
<pre><code>
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Neo4j Batch Importer 1.9-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ batch-import ---
[INFO] Deleting /Users/amoranzea/iag_dev/batch-import/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ batch-import ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.1:compile (default-compile) @ batch-import ---
[INFO] Compiling 51 source files to /Users/amoranzea/iag_dev/batch-import/target/classes
[INFO] 
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) @ batch-import >>>
[INFO] 
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) @ batch-import <<<
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ batch-import ---
Usage: Importer data/dir nodes.csv relationships.csv [node_index node-index-name fulltext|exact nodes_index.csv rel_index rel-index-name fulltext|exact rels_index.csv ....]
Using: Importer sample2/batch.properties ../NEO_HOME/data/graph.db sample2/plant_nodes.csv sample2/plant_rels.csv

Using Existing Configuration File

Importing 4 Nodes took 0 seconds 

Importing 5 Relationships took 0 seconds 

Total import time: 0 seconds 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.302s
[INFO] Finished at: Thu Feb 13 19:05:41 EST 2014
[INFO] Final Memory: 17M/52M
[INFO] ------------------------------------------------------------------------
</pre></code>

Any thoughts?

**Comment by jexp** [comment]
Version 1.9 as the output says can't support labels b/c there are no labels in 1.9

Sent from mobile device

Am 13.02.2014 um 09:15 schrieb Alejandro Moran notifications@github.com:

**Comment by amoranzea** [comment]
Obviously it works. Thanks for everything. By mistake when I switched to branch 20 I did:

<pre><code>
git checkout -b 20
</code></pre>

instead of:

<pre><code>
git checkout 20
</code></pre>

and it just branched master locally.

Thanks
