### ISSUE TITLE
Running import.bat problem

### ISSUE THREAD

**Issue by shaimr** [jexp/batch-import#89]
Hey,

I'm trying to run import.bat and the output: 
Error: Could not find or load main class org.neo4j.batchimport.Importer

Thanks,

Shai.

**Comment by jexp** [comment]
did you use the binary download? You'll have to use maven instead as documented in the readme.

Otherwise it won't work.

Am 26.02.2014 um 08:55 schrieb shaimr notifications@github.com:

**Comment by shaimr** [comment]
You're right.
I did download the wrong files.

Thanks!
